version: 2
defaults: &defaults
    docker:
      - image: cimg/python:3.11.0-browsers
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            sudo apt update
            sudo apt install jq
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker-compose
            
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
run_build: &run_build
          name: Installation of build dependencies.
          command: |
            chmod +x build.sh
            ./build.sh            

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
      
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - run: *run_build

      - deploy:
          command: |
            ./awsconfiguration.sh DEV
            source awsenvconf 
            ./buildenv.sh -e DEV -b member-group-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,member-group-processor_appvar -i member-group-processor

  # Build & Deploy against development backend
  "build-qa":
    <<: *defaults
      
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - run: *run_build

      - deploy:
          command: |
            ./awsconfiguration.sh QA
            source awsenvconf 
            ./buildenv.sh -e QA -b member-group-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e QA -t latest -s qa-global-appvar,member-group-processor_appvar -i member-group-processor            

  "build-prod":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency  
      - run: *install_deploysuite
      - run: *run_build
      - deploy:
          command: |
            ./awsconfiguration.sh PROD
            source awsenvconf 
            ./buildenv.sh -e PROD -b member-group-processor_deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,member-group-processor_appvar -i member-group-processor
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only: [ "develop" ]
      - "build-qa":
          context : org-global
          filters:
            branches:
              only: [ "qa" ]              
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master
